[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyqstars"
version = "1.0.0"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3"
]

[project.scripts]
pyqstars = "pyqstars.__main__:main"
